const login = require('../fixtures/login.json');
describe('Contacts - Company', () => {

    Cypress.on('uncaught:exception', (err, runnable) => {
        return false
    })
    it('Cadastrar empresa', () => {
        cy.Login(login.email, login.password)
        cy.intercept('GET', '**/Account@SupportAccesses@Requests?$filter=Approved+eq+null&$select=Id').as('getAccount')
        cy.wait('@getAccount')
        cy.get(':nth-child(2) > .w-100 > .sc-gKXOVf > #centerRender > #centerRenderMessage > span').click()
        cy.intercept('GET', '**/Account?$expand=City($expand=State,Country),Plan,TotalVoiceIntegration,OtherProperties,HostSet').as('getAccount')
        cy.wait('@getAccount')
        cy.get('[ng-if="(contactsCtrl.self.Profile.ContactsCompanyCreatePermission || contactsCtrl.self.Profile.ContactsPersonCreatePermission) && contactsCtrl.current_mode.EntityId === 1"] > #filter-list').click()
        cy.get('[ng-if="contactsCtrl.self.Profile.ContactsCompanyCreatePermission"] > .white-dropdown-link > .hbox > :nth-child(2)').click()
        cy.get('input[name="contact_name"]').type("Empresa Cypress")
        cy.get('input[name="contact_legal_name"]').type("Empresa Cypress Name")
        cy.get('input[id="select-fk-contactlineofbusiness-29"]').type("Consultoria").wait(2000).type('{enter}')
        cy.get('input[id="select-fk-contactorigin-30"]').type("Facebook").wait(2000).type('{enter}')
        cy.get('input[name="contact_cnpj"]').type("86227242000138")
        cy.get('input[name="contact_phones"]').type("11985264159").tab().tab().tab().tab()
        cy.focused().click().tab({ shift: true })
        cy.focused().click()
        cy.get('input[class="form-control input-sm"]').type("Rua Novo Mundo")
        cy.get('input[name="contact_street_address_line2"]').type("Apartamanto 56B")
        cy.get('input[name="contact_neighborhood"]').type("Mãe Luiza")
        cy.get('input[name="contact_zipcode"]').type("59014410")
        cy.get('input[id="select-fk-contactcity-33"]').type("Natal").wait(2000).type('{enter}')
        cy.get('input[name="contact_email"]').type("empresa.cypress@teste.com")
        cy.get('input[name="contact_website"]').type("www.empresacypress.com")
        cy.get('input[id="select-fk-contactrelationship-35"]').type("Parceiro").wait(2000).type('{enter}')
        cy.get('textarea[name="contact_note"]').type("Cadastramento de empresa, feito de forma automatizada pelo Cypress").tab()
        cy.focused().click().wait(5000)
    })
    it('Listar e Atualizar Empresa', () => {
        cy.Login(login.email, login.password)
        cy.intercept('GET', '**/Account@SupportAccesses@Requests?$filter=Approved+eq+null&$select=Id').as('getAccount')
        cy.wait('@getAccount')
        cy.get('#LeftSideMenuHeader > .d-flex > .sc-gKXOVf').type("Empresa Cypress Name")
        .intercept('GET', '**/GeneralSearch?$top=20&$orderby=Ordination&$expand=Contact($expand=Company($select=Id,Name,CNPJ);$select=Id,Name,TypeId,CPF,CNPJ),Deal($select=Id,Title;$expand=Contact($select=Id,Name,TypeId),Pipeline($select=Id,IconId,SingularUnitName,GenderId)),Order($select=Id,OrderNumber;$expand=Deal($select=Id,Title;$expand=Pipeline($select=Id,IconId,SingularUnitName,GenderId)),Contact($select=Id,Name,TypeId)),Quote($select=Id,QuoteNumber,ReviewNumber;$expand=Deal($select=Id,Title;$expand=Pipeline($select=Id,IconId,SingularUnitName,GenderId)),Contact($select=Id,Name,TypeId)),Lead($select=Id,CompanyName,PersonName),User($select=Id,Name,AvatarUrl),Entity&$filter=contains(StringSearch,%27Empresa%20Cypress%20Name%27)')
        .as('getSearch').wait('@getSearch')
        cy.focused().wait(2000).tab().tab()
        cy.focused().click().wait(2000)
        cy.get('.text-right > .dropdown > .button').click().wait(1000)
        cy.get('[ng-if="$ctrl.model.Editable"] > .white-dropdown-link > .hbox > :nth-child(2)').click()
        cy.get('input[name="contact_name"]').type(" Atualizado")        
        cy.get('input[name="contact_phones"]').type("11985265536").tab().tab().tab().tab().tab()
        cy.focused().click().wait(5000)
    })
    it('Deletar Empresa', () => {
        cy.Login(login.email, login.password)
        cy.intercept('GET', '**/Account@SupportAccesses@Requests?$filter=Approved+eq+null&$select=Id').as('getAccount')
        cy.wait('@getAccount')
        cy.get('#LeftSideMenuHeader > .d-flex > .sc-gKXOVf').type("Empresa Cypress Name")
        .intercept('GET', '**/GeneralSearch?$top=20&$orderby=Ordination&$expand=Contact($expand=Company($select=Id,Name,CNPJ);$select=Id,Name,TypeId,CPF,CNPJ),Deal($select=Id,Title;$expand=Contact($select=Id,Name,TypeId),Pipeline($select=Id,IconId,SingularUnitName,GenderId)),Order($select=Id,OrderNumber;$expand=Deal($select=Id,Title;$expand=Pipeline($select=Id,IconId,SingularUnitName,GenderId)),Contact($select=Id,Name,TypeId)),Quote($select=Id,QuoteNumber,ReviewNumber;$expand=Deal($select=Id,Title;$expand=Pipeline($select=Id,IconId,SingularUnitName,GenderId)),Contact($select=Id,Name,TypeId)),Lead($select=Id,CompanyName,PersonName),User($select=Id,Name,AvatarUrl),Entity&$filter=contains(StringSearch,%27Empresa%20Cypress%20Name%27)')
        .as('getSearch').wait('@getSearch')
        cy.focused().wait(2000).tab().tab()
        cy.focused().click().wait(2000)
        cy.get('.text-right > .dropdown > .button').click().wait(1000)
        cy.get('[ng-if="$ctrl.model.Deletable"] > .white-dropdown-link > .hbox > :nth-child(2)').click().wait(2000)
        cy.get('[ng-if="!hardCheckWord"] > .button-action').click(5000)
    })
})